### ISSUE TITLE
sed and echo not working as intended. 

### ISSUE THREAD

**Issue by fastzombies** [theGeeBee/DocumentServerOnFreeBSD#1]
Thank you for this script, it is exactly what I needed.  However, these lines do not seem to be working as intended:

https://github.com/theGeeBee/DocumentServerOnFreeBSD/blob/3302a0a507bd1d61ad11a82f1132383e3e723c2d/install.sh#L81-L82

The sed line adds an [include] at the beginning of uncommented lines, replacing the first letter.  The echo doesn't seem to go anywhere.  I'm not sure what either of these are supposed to do.  Please let me know what the intention is so I can try some fixes.  Thank you.

**Comment by theGeeBee** [comment]
Hi,

I've actually been out of action for a while. 
I just pushed the latest commit which makes more sense of what you just pointed out.

Try the latest now.

**Comment by fastzombies** [comment]
Thank you.  QUite a bit has changed so this issues no longer applies.  I'm trying the new script now.
