### ISSUE TITLE
502 Bad Gateway nginx

### ISSUE THREAD

**Issue by fastzombies** [theGeeBee/DocumentServerOnFreeBSD#7]
All the previous issues are either resolved or being resolved.  I was able to get through the script successfully but unfortunately there is some bad configuration.  I will try to rebuild from scratch and see if this resolves.  Opening issue now in case the cause is known.

**Comment by theGeeBee** [comment]
After updating to the latest build of the document server, I am also experiencing this. 
There is an error in the packaged nginx example configuration files as well. Working to resolve soon.

**Comment by fastzombies** [comment]
I tried installing on a VM via docker-compose with no success.  I restart this jail to take a look and see if I can find anything and suddenly it seemed to work.  I would attach a screenshot but github won't let me, but there is a simple welcome screen that tells Document Server is running.

However, after installing the NextClould connector and trying to configure, NextCloud will not open OnlyOffice to edit documents.  I'm sure that is beyond the scope of this issue.

So it is possible that this script is ok and a restart is necessary after it completes.

**Comment by theGeeBee** [comment]
Hi,

Apologies, I've actually been nursing some health issues and haven't had any time yet. 
If it is working on your machine, that's good for now.

Regarding your issue, on Nextcloud config for OnlyOffice, you might need to remove the Secret Text, the "placeholder" value is actually a variable that is filled. If it works after removing the secret, you can then proceed to start securing your installation.

**Comment by fastzombies** [comment]
No problem, no urgency here.  I can workaround for now.  I hope you get better.

Since a restart seemed to help I am closing this issue.  If it comes up again we can re-open.  I will open a new issue for the connector to keep issues focused.

**Comment by fastzombies** [comment]
Try again to close the issue.
